#!/bin/sh
export PATH=/usr/local/cs:$PATH

echo "++++++++++++++++dash tests+++++++++++++"
echo "---------------------test 2--------------------"
head -c 1MB /dev/urandom | tr -s A-Z a-z | cat > b
times
/usr/bin/time -f "Max resident set size:\t%M\nBlock Input\t%I\nBlock Output\t%O\nPage Reclaims:\t%R\nPage Faults:\t%F\nVoluntary context switches:\t%w\nInvoluntary context switches:\t%c\n"\
 head -c 1MB /dev/urandom | tr -s A-Z a-z | cat > b
rm b
